use_frameworks!

target 'WFFCategory_Example' do
  pod 'WFFCategory', :path => '../'

  target 'WFFCategory_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
